name: gfn-optimization
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Scientific Computing Stack
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  
  # Quantum Chemistry
  - pyscf>=2.0.0
  - ase>=3.22.0
  
  # Configuration & I/O
  - toml
  
  # Development & Debugging
  - ipython
  - jupyter
  
  # HPC Utilities
  - mpi4py  # For parallel computing if needed
  
  # Additional utilities
  - tqdm  # Progress bars
  - psutil  # System monitoring
  
  # pip dependencies (packages not available via conda)
  - pip
  - pip:
    - tblite-python  # Try pip version of tblite
    
# Note: tblite might need special handling on HPC
# Consider building from source or using modules if available 
